#------------------------------------------------
# INITIAL DEFINITIONS
#------------------------------------------------
%define PNAME vcftools
Summary: A set of tools for working with VCF files, such as those generated by the 1000 Genomes Project.
Version: 0.1.12
Release: 1
License: GPLv3
Group: Applications/Life Sciences
Source:  http://tophat.cbcb.umd.edu/downloads/%{PNAME}_%{version}b.tar.gz
Packager: TACC - vaughn@tacc.utexas.edu
#Prefix: /opt/apps

## System Definitions
%include ./include/system-defines.inc
%include ./include/%{PLATFORM}/rpm-dir.inc
## Compiler Family Definitions
# %include ./include/%{PLATFORM}/compiler-defines.inc
## MPI Family Definitions
# %include ./include/%{PLATFORM}/mpi-defines.inc
## directory and name definitions for relocatable RPMs
%include ./include/name-defines.inc

%define MODULE_VAR  %{MODULE_VAR_PREFIX}VCFTOOLS

## PACKAGE DESCRIPTION
%description
Vcftools is a suite of functions for use on genetic variation data in the form of VCF and BCF files. The tools provided will be used mainly to summarize data, run calculations on data, filter out data, and convert data into other useful file formats.

#------------------------------------------------

## PREP
# Use -n <name> if source file different from <name>-<version>.tar.gz
%prep
rm -rf $RPM_BUILD_ROOT/%{INSTALL_DIR}
rm -rf $RPM_BUILD_ROOT/%{MODULE_DIR}

## SETUP
%setup -n vcftools_0.1.12b

## BUILD
%build

#------------------------------------------------
# INSTALL
#------------------------------------------------
%install

# Start with a clean environment
%include ./include/%{PLATFORM}/system-load.inc
mkdir -p $RPM_BUILD_ROOT/%{INSTALL_DIR}

#------------------------------------------------
## Install Steps Start

module swap $TACC_FAMILY_COMPILER gcc
module load perl/5.14

export PERL5LIB=$PERL5LIB:./perl/

mkdir -p $PWD/tmpinstall
make PREFIX=$PWD/tmpinstall
make install
mkdir -p $PWD/tmpinstall/bin/man1 && cp cpp/vcftools.1 $PWD/tmpinstall/bin/man1

cp -R tmpinstall/* $RPM_BUILD_ROOT/%{INSTALL_DIR}

## Install Steps End
#------------------------------------------------

#------------------------------------------------
# MODULEFILE CREATION
#------------------------------------------------
mkdir -p $RPM_BUILD_ROOT/%{MODULE_DIR}

#------------------------------------------------
## Modulefile Start
cat > $RPM_BUILD_ROOT/%{MODULE_DIR}/%{version}.lua << 'EOF'
help(
[[
The %{PNAME} module file defines the following environment variables:
%{MODULE_VAR}_DIR and %{MODULE_VAR}_BIN for the location of the %{PNAME}
distribution.

Version %{version}
]]
)

whatis("Name: %{PNAME}")
whatis("Version: %{version}")
whatis("Category: computational biology, genomics")
whatis("Keywords: Biology, Genomics, Variation")
whatis("URL: https://vcftools.github.io/")
whatis("Description: A set of tools written in Perl and C++ for working with VCF files.")

prepend_path("PATH",              "%{INSTALL_DIR}/bin")
prepend_path("MANPATH",              "%{INSTALL_DIR}/bin/man1")
prepend_path("PERL5LIB",              "%{INSTALL_DIR}/lib/perl5/site_perl")

setenv (     "%{MODULE_VAR}_DIR", "%{INSTALL_DIR}")
setenv (     "%{MODULE_VAR}_LIB", "%{INSTALL_DIR}/lib")
setenv (     "%{MODULE_VAR}_PERL5LIB", "%{INSTALL_DIR}/lib/perl5/site_perl")
prereq("perl/5.14")

EOF

## Modulefile End
#------------------------------------------------

## Lua syntax check
if [ -f $SPEC_DIR/checkModuleSyntax ]; then
    $SPEC_DIR/checkModuleSyntax $RPM_BUILD_ROOT/%{MODULE_DIR}/%{version}.lua
fi

## VERSION FILE
cat > $RPM_BUILD_ROOT%{MODULE_DIR}/.version.%{version} << 'EOF'
#%Module3.1.1#################################################
##
## version file for %{PNAME}-%{version}
##

set     ModulesVersion      "%{version}"
EOF

#------------------------------------------------
# FILES SECTION
#------------------------------------------------
#%files -n %{name}-%{comp_fam_ver}
%files
%defattr(-,root,install,)
%{INSTALL_DIR}
%{MODULE_DIR}

## POST
%post

## CLEAN UP
%clean
# Make sure we are not within one of the directories we try to delete
cd /tmp

# Remove the installation files now that the RPM has been generated
rm -rf $RPM_BUILD_ROOT
