Name:       smrt
Summary:    SMRT Analysis Suite
Version:    2.3.0p2
Release:    1
License:    GPL
Vendor:     PacBio
Group: Applications/Life Sciences
Source:     smrtanalysis.tar.gz
Packager:   TACC - gzynda@tacc.utexas.edu
Prefix:    /opt/apps

#------------------------------------------------
# INITIAL DEFINITIONS
#------------------------------------------------

## System Definitions
%include ./include/system-defines.inc
%include ./include/%{PLATFORM}/rpm-dir.inc
## Compiler Family Definitions
%include ./include/%{PLATFORM}/compiler-defines.inc
## MPI Family Definitions
# %include ./include/%{PLATFORM}/mpi-defines.inc

%define INSTALL_DIR %{APPS}/%{comp_fam_ver}/%{name}/%{version}
%define MODULE_DIR  %{APPS}/%{comp_fam_ver}/%{MODULES}/%{name}
%define MODULE_VAR  %{MODULE_VAR_PREFIX}SMRT
%define PNAME       smrt

%define __os_install_post    \
    /usr/lib/rpm/redhat/brp-compress \
    %{!?__debug_package:/usr/lib/rpm/redhat/brp-strip %{__strip}} \
    /usr/lib/rpm/redhat/brp-strip-static-archive %{__strip} \
    /usr/lib/rpm/redhat/brp-strip-comment-note %{__strip} %{__objdump} \
%{nil}

%package -n %{name}-%{comp_fam_ver}
Summary:   BSMAP for Methylation
Group:     Applications/Life Sciences

## PACKAGE DESCRIPTION
%description
%description -n %{name}-%{comp_fam_ver}
The SMRT Analysis software suite performs assembly and variant detection analysis of sequencing data generated by the Pacific Biosciences instrument.

## PREP
%prep
[ -n "$RPM_BUILD_ROOT" -a "$RPM_BUILD_ROOT" != / ] && rm -rf ${RPM_BUILD_ROOT}

## SETUP
# Use -n <name> if source file different from <name>-<version>.tar.gz
%setup -n smrtanalysis
#%setup -n %{PNAME}-%{version}

## BUILD
%build

#------------------------------------------------
# INSTALL
#------------------------------------------------
%install

# Start with a clean environment
%include ./include/%{PLATFORM}/system-load.inc
mkdir -p $RPM_BUILD_ROOT/%{INSTALL_DIR}

## Install Steps Start

rm tmpdir && ln -s /tmp tmpdir
cp -r * $RPM_BUILD_ROOT/%{INSTALL_DIR}/

## Install Steps End

#------------------------------------------------
# MODULEFILE CREATION
#------------------------------------------------
rm   -rf $RPM_BUILD_ROOT/%{MODULE_DIR}
mkdir -p $RPM_BUILD_ROOT/%{MODULE_DIR}

#------------------------------------------------
## Modulefile Start
cat > $RPM_BUILD_ROOT/%{MODULE_DIR}/%{version}.lua << 'EOF'
help (
[[
Documentation for %{PNAME} is available online at the publisher website: https://github.com/PacificBiosciences/SMRT-Analysis

To use interactively, run:
	smrtshell

To run though a job script, run:
	smrtpipe

Automatic job submission is not currently supported, but more information about running analyses can be found at: https://github.com/PacificBiosciences/SMRT-Analysis/wiki/SMRT-Pipe-Reference-Guide-v2.3.0

For convenience %{MODULE_VAR}_DIR points to the installation directory. 
PATH has been updated to include smrtcmds.

Version %{version}
]])
whatis("Name: ${PNAME}")
whatis("Version: %{version}")
whatis("Category: computational biology, genomics, qc, assembly")
whatis("Keywords: pacbio, smrt")
whatis("Description: SMRT Analysis Suite - Suite for processing PacBio data")
whatis("URL: https://github.com/PacificBiosciences/SMRT-Analysis")

setenv("%{MODULE_VAR}_DIR","%{INSTALL_DIR}/")
setenv("SMRT_ROOT","%{INSTALL_DIR}")
prepend_path("PATH","%{INSTALL_DIR}/smrtcmds/bin")
EOF
## Modulefile End
#------------------------------------------------

## Lua syntax check
if [ -f $SPEC_DIR/checkModuleSyntax ]; then
    $SPEC_DIR/checkModuleSyntax $RPM_BUILD_ROOT/%{MODULE_DIR}/%{version}.lua
fi

#--------------
#  Version file.
#--------------

cat > $RPM_BUILD_ROOT%{MODULE_DIR}/.version.%{version} << 'EOF'
#%Module3.1.1#################################################
##
## version file for %{PNAME}-%{version}
##
set     ModulesVersion      "%{version}"
EOF

#------------------------------------------------
# FILES SECTION
#------------------------------------------------
%files -n %{name}-%{comp_fam_ver}

# Define files permisions, user and group
%defattr(755,root,root,-)
%{INSTALL_DIR}
%{MODULE_DIR}

#------------------------------------------------
# CLEAN UP SECTION
#------------------------------------------------
%post
%clean
[ -n "$RPM_BUILD_ROOT" -a "$RPM_BUILD_ROOT" != / ] && rm -rf ${RPM_BUILD_ROOT}
